keywords:
  - sheldon
  - cooper
response: Bazinga!!
credsPath: /Users/shobhits/Documents/shobhit/repos/self/redditer/creds.yml
submissionsFile: /usr/local/share/filtered-submissions.csv
commentsFile: /usr/local/share/filtered-comments.csv